# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = 'ubuntu/trusty64'

  (1..3).each do |i|
    config.vm.define "reader-#{i}" do |node|
      node.vm.network 'forwarded_port', guest: 6379, host: 6379 + i
    end
    config.vm.define 'processor' do |node|
      node.vm.network 'forwarded_port', guest: 6379, host: 6378
    end
    config.vm.define 'ui' do |node|
    end
  end

  config.vm.provision 'ansible' do |ansible|
    ansible.groups = {
      'readers' => ['reader-1', 'reader-2'],
      'processors' => ['processor'],
      'ui' => ['ui'],
    }
    ansible.playbook = 'playbook.yml'
  end

  config.vm.synced_folder '../', '/ipp'
end
